// index.tsx
'use client'

import React, { useEffect, useState } from 'react'

import { AdLogoSvg, AdProgressBar } from 'nucleify'

import './_index.scss'

export function NucScreenLoader(): React.JSX.Element | null {
  const [isVisible, setIsVisible] = useState(true)

  useEffect(() => {
    const timeout = setTimeout(() => {
      setIsVisible(false)
    }, 1500)

    return () => clearTimeout(timeout)
  }, [])

  if (!isVisible) {
    return null
  }

  return (
    <div className="screen-loader-container">
      <div className="screen-loader-content">
        <div className="loader-image">
          <AdLogoSvg nuiType="main" dimensions={125} />
        </div>

        <AdProgressBar
          mode="indeterminate"
          style={{ width: '100px', height: '10px' }}
        />
      </div>
    </div>
  )
}

// index.vue
<template>
  <div class="screen-loader-container">
    <div class="screen-loader-content">
      <ad-logo-svg class="loader-image" ad-type="main" dimensions="125" />
      <ad-progress-bar mode="indeterminate" width="100px" height="10px" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { AdLogoSvg, hideLoader } from 'nucleify'

onMounted(() => {
  hideLoader()
})
</script>

<style lang="scss">
@import 'index';
</style>
